ui_width = 314;  // Equip screen width
ui_height = 174; // Equip screen height
ui_width_midpoint = 157;
ui_height_midpoint = 87;
ui_x = 3; // Equip screen x postion
ui_y = 3; // Equip screen x postion
show_equip = false;
op_space = global.op_space;
op_margin = global.op_margin;
op_border = global.op_border;
//p_length = ds_list_size(global.party);
text_size = .085;
selected_character = 0;